### ISSUE TITLE
Plugin.php needs to be updated for Kanboard 1.0.20

### ISSUE THREAD

**Issue by Chaosmeister** [sebastiantiede/kanboard-plugin-wysiwyg#2]
namespace **Kanboard**\Plugin\wysiwyg;
use **Kanboard**\Core\Plugin\Base;

**Comment by sebastiantiede** [comment]
Thanks, fixed:
https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/commit/77f6c40967d4c198bed5151d83e5e273e35a6b5a
