### ISSUE TITLE
Layout Issue - textbox intersects frame

### ISSUE THREAD

**Issue by Chaosmeister** [sebastiantiede/kanboard-plugin-wysiwyg#3]
The textinput box has a visual issue in the taskview.

**TaskView:**
![image](https://cloud.githubusercontent.com/assets/13346344/10752685/b7f8dc4c-7c8b-11e5-84a4-75d907558023.png)

it looks good in every other place.

**Comment by sebastiantiede** [comment]
Fixed with the latest commit https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/commit/4797ba44f8c2d2edf6a7387d85463ea6bfa120c8
