### ISSUE TITLE
[FR] (un-)ordered list on selection

### ISSUE THREAD

**Issue by Chaosmeister** [sebastiantiede/kanboard-plugin-wysiwyg#4]
I'd like to make a list out of a selection:
![image](https://cloud.githubusercontent.com/assets/13346344/10753210/b9e646f8-7c8f-11e5-8e37-7651f740e044.png)

The button only adds the "1."/"*" in the first line of the selection:
![image](https://cloud.githubusercontent.com/assets/13346344/10753294/5a0e2f10-7c90-11e5-97d9-481764502d3b.png)

**Comment by sebastiantiede** [comment]
Thanks for reporting. I'm looking for a better WYSIWYG plugin. 
Maybe I need to write a editor.
I'll keep you up to date.

**Comment by Chaosmeister** [comment]
I tried the same thing with the markdown plugin that is used on stackoverflow.
It behaves a little bit different but still not like I would like it.

It takes the selection, removes the linebreaks and then takes uses the whole selection as item number 1.

**Comment by sebastiantiede** [comment]
StackEdit is great. But it isn't embeddable (according to https://github.com/benweet/stackedit/issues/150).

anyway: next update of this plugin comes with a fork of [pagedown](https://github.com/ujifgc/pagedown)

**Comment by sebastiantiede** [comment]
ok: [pagedown is the new editor](https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/commit/4797ba44f8c2d2edf6a7387d85463ea6bfa120c8). Now it's the same like on stackoverflow.
