### ISSUE TITLE
Sidebyside feature not working

### ISSUE THREAD

**Issue by Chaosmeister** [sebastiantiede/kanboard-plugin-wysiwyg#5]
The sidebyside button is not working like it is supposed to be.
No dynamic preview is shown but the textbox is resized.

tested on:
Windows 8.1 with latest Chrome

**Comment by sebastiantiede** [comment]
Fixed with the latest commit https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/commit/4797ba44f8c2d2edf6a7387d85463ea6bfa120c8
