### ISSUE TITLE
[FR] add an installation tutorial

### ISSUE THREAD

**Issue by Chaosmeister** [sebastiantiede/kanboard-plugin-wysiwyg#6]
I'm not sure if this should be an issue but I also don't know how else to communicate with you.

I had a pretty hard time setting up your plugin.
I learned a lot on the way (Nodejs and NPM / Bower) but I'm unsure if everyone is going to like working through all this, so I'd suggest extending the installation instructions. I will write what would have helped me:

**Comment by Chaosmeister** [comment]
# Dependencies

[Meltdown](https://github.com/iphands/Meltdown)

# Installation

Create a directory **"wysiwyg"** in the kanboard/plugins directory. It is important to use that exact name!  
[Download the Sourcecode](https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/archive/master.zip)
Extract the **source files** into the created directory.

Install **Bower** with NPM.
1. Download [NodeJS/NPM](https://nodejs.org/).
2. Use NPM to install Bower: `$ npm install -g bower` - [Additional help](https://www.npmjs.com/package/bower)
3. Install [Git](https://git-scm.com/downloads)

Install the **bower.json** with Bower. This will install Meltdown and all of Meltdowns dependencies:
1. `bower install bower.json`

## Done!

**Comment by Chaosmeister** [comment]
Or as pasteable code: http://pastebin.com/k2pyW2XK

**Comment by sebastiantiede** [comment]
Great, thanks! https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/commit/b4af43f4f7650578789cc5f3de618020be3952e6
