### ISSUE TITLE
Package App States=bower.json not found

### ISSUE THREAD

**Issue by letsgo008** [sebastiantiede/kanboard-plugin-wysiwyg#7]
bower install --allow-root bower.json
bower cached        git://github.com/Kalitte/app-states.git#0.6.9
bower validate      0.6.9 against git://github.com/Kalitte/app-states.git#*
bower ENOTFOUND     Package App States=bower.json not found

**Comment by letsgo008** [comment]
Unable to find a suitable version for webcomponentsjs, please choose one:
    1) webcomponentsjs#~0.5.4 which resolved to 0.5.5 and is required by App States#0.6.9
    2) webcomponentsjs#\* which resolved to 0.5.5 and is required by core-component-page#0.5.6
    3) webcomponentsjs#^0.6.0 which resolved to 0.6.3 and is required by polymer#0.5.6

Prefix the choice with ! to persist it to bower.json

**Comment by sebastiantiede** [comment]
please try `bower install --allow-root`
