### ISSUE TITLE
The Editor is not working since the latest kanboard update 1.0.25

### ISSUE THREAD

**Issue by Chaosmeister** [sebastiantiede/kanboard-plugin-wysiwyg#8]
The Editor is unavailable in almost all popups from the new task dropdown menu:

![image](https://cloud.githubusercontent.com/assets/13346344/12948578/32f458a2-d003-11e5-9c6d-060fbc1a7de6.png)

![image](https://cloud.githubusercontent.com/assets/13346344/12948548/0799c2c8-d003-11e5-8935-9ea27f306aac.png)

**Comment by sebastiantiede** [comment]
Thanks for reporting!
Fix: https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/commit/69830bb2973c56908a0f9e641c76199d76039630

**Comment by Chaosmeister** [comment]
Hey good job on the fast fix for the comments popup.

On "Edit the description" it is still missing though.
I'm not sure if there are any more occasions.

I can't re-open the issue, so I will create a new one in a few days for the case, you're not notified about this.
