### ISSUE TITLE
The Editor is not working since the latest kanboard update 1.0.25 - upd

### ISSUE THREAD

**Issue by Chaosmeister** [sebastiantiede/kanboard-plugin-wysiwyg#9]
#8 fixed the editor for comments.

On "Edit the description" it is still missing though.

**Comment by sebastiantiede** [comment]
Thanks again, it's fixed: https://github.com/sebastiantiede/kanboard-plugin-wysiwyg/commit/7f02181551a2c03f78cfc1856c23a7c3348ff2c9
